GET http://localhost:3000/contacts HTTP/1.1

###
# GET /contacts/:id
GET http://localhost:3000/contacts/645d4a3f121b39d3007fabfc HTTP/1.1

###
#  This contact does not exist yet, click send request to see if it gets created
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Matias",
  "lastName": "Villar",
  "email": "ivan@gmail.com",
  "favoriteColor": "Red",
  "birthday": "1964-07-19"
}

###

PUT http://localhost:3000/contacts/644874f5ebeca1f2559b5897 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Agustin"
}

###

DELETE http://localhost:3000/contacts/64487463ebeca1f2559b5893 HTTP/1.1

